name: fe
on:
    push:
      branches: [ master ]
    workflow_dispatch:  # Allow manual invocation of the workflow
permissions:
     id-token: write
     contents: write
env:
  AWS_REGION :  us-east-1
#   REACT_APP_API_BASE_URL: ${{ secrets.DRFLEET_REACT_APP_API_BASE_URL }}
#   REACT_APP_CLOUD_FRONT_BASE_URL: ${{ secrets.REACT_APP_CLOUD_FRONT_BASE_URL }}
jobs:
  GenerativeAI-UI-POC:
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: reactapp/simple-reactjs-app
    permissions:
       id-token: write
       contents: write
    steps:

       - name: Check out code
         uses: actions/checkout@v2

       - name: Setup node
         uses: actions/setup-node@v1

      #  - name: API URL variable
      #    uses: CallePuzzle/envvar-to-dotenv-action@0.1.0
      #    with:
      #      variableNames: ^REACT_(APP.*)

       - name: Use Node.js 16.x
         uses: actions/setup-node@v1
         with:
           node-version: 16.x

       - name: Install npm
         run : npm install

       - name: Build static file
         run: npm run build
   
       - name: Share artifact inside workflow
         run: pwd

       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

       - name: Deploy static site to S3 bucket
         run: aws s3 sync ./build s3://samplereactapplication/

      #  - name: Invalidate CloudFront
      #    run: aws cloudfront create-invalidation --distribution-id E22QI9TUPXRBVL --paths "/*"